"""
Operational fraud detection metrics (skill: metricas-fraude).

For every model, reports:
  - PR-AUC     (primary — imbalanced classes)
  - ROC-AUC    (secondary)
  - Recall @ precision=0.90  ("how much fraud do we catch with 90% alert accuracy?")
  - F1 at optimal threshold + confusion matrix
  - Business translation: alerts/day and % undetected fraud at BRS scale (500K accounts)
"""

import numpy as np
import pandas as pd
from sklearn.metrics import (
    average_precision_score,
    roc_auc_score,
    precision_recall_curve,
    f1_score,
    confusion_matrix,
)


BRS_ACCOUNTS      = 500_000   # BRS total accounts
BRS_FRAUD_RATE    = 0.0193    # from EDA: 1.93% fraud nodes
BRS_REVIEWS_PER_DAY = BRS_ACCOUNTS / 365   # baseline if you reviewed everything


def recall_at_precision(y_true, y_score, target_precision=0.90):
    """Recall achieved when precision threshold is met."""
    prec, rec, thr = precision_recall_curve(y_true, y_score)
    # prec/rec are ordered by decreasing threshold
    mask = prec >= target_precision
    if not mask.any():
        return 0.0, None
    # sklearn orders by increasing threshold → prec increases, rec decreases
    # first True index = highest recall point that still meets the precision target
    idx = np.where(mask)[0][0]
    return float(rec[idx]), float(thr[idx]) if idx < len(thr) else None


def optimal_f1_threshold(y_true, y_score):
    """Find threshold that maximises F1."""
    prec, rec, thr = precision_recall_curve(y_true, y_score)
    f1s = 2 * prec * rec / (prec + rec + 1e-9)
    idx = np.argmax(f1s[:-1])   # last point has rec=1, prec undefined
    return float(thr[idx]), float(f1s[idx])


def business_translation(cm, dataset_n_accounts, dataset_fraud_rate,
                          brs_accounts=BRS_ACCOUNTS, brs_fraud_rate=BRS_FRAUD_RATE):
    """
    Scale confusion matrix from the test set to BRS volume.
    Returns dict with alerts/day and pct_fraud_missed.
    """
    tn, fp, fn, tp = cm.ravel()
    # scale factor: how many BRS accounts per test account
    scale = (brs_accounts * brs_fraud_rate) / max((tp + fn), 1)
    tp_s = tp * scale
    fp_s = fp * scale
    fn_s = fn * scale

    # daily figures (BRS reviews alerts generated by the model every day)
    # assume 1/365 of accounts transact per day on average
    daily_alerts    = (tp_s + fp_s) / 365
    daily_fraud_tp  = tp_s / 365
    pct_missed      = fn / max(tp + fn, 1) * 100

    return {
        "daily_alerts":   round(daily_alerts),
        "daily_fraud_tp": round(daily_fraud_tp),
        "pct_fraud_missed": round(pct_missed, 1),
        "scale_factor":   round(scale, 1),
    }


def evaluate_model(name: str, y_true, y_score,
                   dataset_n_accounts: int = 1500,
                   dataset_fraud_rate: float = 0.0193,
                   target_precision: float = 0.90) -> dict:
    """
    Full metric suite for one model. Returns results dict.
    Also prints a formatted report.
    """
    pr_auc   = average_precision_score(y_true, y_score)
    roc_auc  = roc_auc_score(y_true, y_score)
    rec_p90, thr_p90 = recall_at_precision(y_true, y_score, target_precision)
    opt_thr, opt_f1  = optimal_f1_threshold(y_true, y_score)

    y_pred = (y_score >= opt_thr).astype(int)
    cm = confusion_matrix(y_true, y_pred)
    biz = business_translation(cm, dataset_n_accounts, dataset_fraud_rate)

    results = {
        "model":          name,
        "pr_auc":         round(pr_auc, 4),
        "roc_auc":        round(roc_auc, 4),
        "rec_at_p90":     round(rec_p90, 4),
        "thr_at_p90":     round(thr_p90, 4) if thr_p90 else None,
        "f1_optimal":     round(opt_f1, 4),
        "threshold_opt":  round(opt_thr, 4),
        "confusion_matrix": cm.tolist(),
        **{f"biz_{k}": v for k, v in biz.items()},
    }

    _print_report(name, results, cm, biz, target_precision)
    return results


def _print_report(name, r, cm, biz, target_precision):
    tn, fp, fn, tp = cm.ravel()
    print(f"\n{'='*55}")
    print(f"  Modelo: {name}")
    print(f"{'='*55}")
    print(f"  PR-AUC       (primaria) : {r['pr_auc']:.4f}")
    print(f"  ROC-AUC      (secundaria): {r['roc_auc']:.4f}")
    print(f"  Recall @ precision={target_precision:.0%}: {r['rec_at_p90']:.4f}")
    print(f"  F1 óptimo               : {r['f1_optimal']:.4f}  (threshold={r['threshold_opt']:.3f})")
    print(f"\n  Matriz de confusión (threshold óptimo F1):")
    print(f"              Pred legítimo  Pred fraude")
    print(f"  Real legítimo    {tn:>6}        {fp:>6}")
    print(f"  Real fraude      {fn:>6}        {tp:>6}")
    print(f"\n  Traducción a BRS (500K cuentas, escala {biz['scale_factor']}x):")
    print(f"  → Alertas/día que revisa un analista: {biz['daily_alerts']:>4}")
    print(f"  → De las cuales son fraude real:      {biz['daily_fraud_tp']:>4}")
    print(f"  → % del fraude que NO se detecta:     {biz['pct_fraud_missed']:>4.1f}%")


def build_comparison_table(results_list: list[dict]) -> pd.DataFrame:
    cols = ["model", "pr_auc", "roc_auc", "rec_at_p90", "f1_optimal",
            "biz_daily_alerts", "biz_daily_fraud_tp", "biz_pct_fraud_missed"]
    df = pd.DataFrame(results_list)[cols]
    df.columns = ["Modelo", "PR-AUC", "ROC-AUC",
                  f"Recall@P90", "F1-óptimo",
                  "Alertas/día (BRS)", "Fraude detectado/día (BRS)", "% Fraude no detectado"]
    return df.set_index("Modelo")
