"""
Export model outputs as static JSONs consumed by the Next.js dashboard.

Outputs (all in dashboard/public/data/):
  kpis.json              — headline metrics for the overview page
  pr_curves.json         — PR curve points for every trained model found
  score_distribution.json — histogram of GNN scores (fraud vs legit)
  rings.json             — top fraud rings with node scores and amounts
  top_accounts.json      — top-200 accounts by GNN risk score
  entities.json          — entity network (personas + empresas + links)
  cases.json             — pre-generated alert cases for case management
"""

import hashlib
import json
import random
from datetime import datetime, timedelta
from pathlib import Path

import numpy as np
import pandas as pd
import torch
import torch.nn.functional as F
import networkx as nx
import yaml

from sklearn.metrics import precision_recall_curve, average_precision_score

from src.features import build_node_features, get_feature_matrix
from src.models.graphsage import GraphSAGE
from src.evaluate import recall_at_precision


# ── texturas de transacción (canal / concepto / moneda) ──────────────────────
# Derivadas de forma determinística a la hora de exportar, para que el extracto
# se vea como uno real (transferencia CBU/CVU, débito, POS…) en lugar de un
# simple src→dst. No alteran el dataset ni el modelo: es capa de presentación.
_CANALES_BIG   = ["Transferencia CBU", "Transferencia inmediata CBU", "Transferencia MEP"]
_CANALES_MED   = ["Transferencia CVU", "Transferencia CBU", "Débito automático"]
_CANALES_SMALL = ["Pago con débito (POS)", "Pago de servicios (VEP)", "Transferencia CVU"]

_CONCEPTOS_BIZ     = ["Pago a proveedor", "Cancelación de factura A", "Pago de honorarios",
                      "Aporte de capital", "Pago de servicios profesionales"]
_CONCEPTOS_MERCH   = ["Compra", "Pago con tarjeta", "Liquidación de venta", "Pago de mercadería"]
_CONCEPTOS_PERSON  = ["Transferencia entre cuentas", "Préstamo entre particulares",
                      "Devolución de dinero", "Pago de alquiler", "Reintegro"]


def _stable_hash(*parts) -> int:
    return int(hashlib.md5("|".join(str(p) for p in parts).encode()).hexdigest()[:8], 16)


def _txn_meta(src: str, dst: str, amount: float, dst_type: str | None) -> dict:
    """Deterministic channel/concept/currency for a transaction (presentation)."""
    h = _stable_hash(src, dst, round(float(amount), 2))
    if amount >= 50000:
        canal = _CANALES_BIG[h % len(_CANALES_BIG)]
    elif amount >= 3000:
        canal = _CANALES_MED[h % len(_CANALES_MED)]
    else:
        canal = _CANALES_SMALL[h % len(_CANALES_SMALL)]
    pool = (_CONCEPTOS_MERCH if dst_type == "merchant"
            else _CONCEPTOS_BIZ if dst_type == "business"
            else _CONCEPTOS_PERSON)
    return {"canal": canal, "concepto": pool[h % len(pool)], "moneda": "ARS"}
from src import rules_engine

# Ordered so the dashboard lists baselines before the GNNs.
MODEL_SCORE_FILES = {
    "Logistic Regression": "scores_logreg.npy",
    "XGBoost":             "scores_xgboost.npy",
    "Node2Vec + XGBoost":  "scores_node2vec.npy",
    "GAT":                 "scores_gat.npy",
    "GraphSAGE":           "scores_graphsage.npy",
}


def load_config(path="config/config.yaml"):
    with open(path) as f:
        return yaml.safe_load(f)


def _save(obj, path):
    Path(path).parent.mkdir(parents=True, exist_ok=True)
    with open(path, "w") as f:
        json.dump(obj, f, separators=(",", ":"))
    kb = Path(path).stat().st_size / 1024
    print(f"  -> {path}  ({kb:.1f} KB)")


# ── load artefacts ────────────────────────────────────────────────────────────

def _load_entity_tables(raw: str):
    """Load entity CSVs if they exist (generated by generate_entities.py)."""
    def _try(name):
        p = Path(raw) / name
        return pd.read_csv(p) if p.exists() else pd.DataFrame()

    return (
        _try("personas.csv"),
        _try("empresas.csv"),
        _try("titularidades.csv"),
        _try("directores.csv"),
        _try("pep_flags.csv"),
        _try("sanctions_hits.csv"),
    )


def load_all(cfg):
    raw       = cfg["data"]["raw_dir"]
    processed = cfg["data"]["processed_dir"]

    acc = pd.read_csv(f"{raw}/accounts.csv")
    txn = pd.read_csv(f"{raw}/transactions.csv")

    data = torch.load(f"{processed}/graph.pt", weights_only=False)

    ckpt  = torch.load("models/graphsage_best.pt", weights_only=False)
    model = GraphSAGE(data.num_node_features, **{
        k: ckpt["config"][k] for k in ["hidden_channels", "num_layers", "dropout"]
    })
    model.load_state_dict(ckpt["model_state"])
    model.eval()

    with torch.no_grad():
        scores_all = F.softmax(model(data.x, data.edge_index), dim=1)[:, 1].numpy()

    scores_by_model = {}
    for name, fname in MODEL_SCORE_FILES.items():
        path = Path(processed) / fname
        if path.exists():
            scores_by_model[name] = np.load(path)
        else:
            print(f"  (omitido: {name} — {fname} no encontrado)")
    scores_gnn = scores_by_model["GraphSAGE"]
    y_test     = np.load(f"{processed}/y_test.npy")

    return acc, txn, data, scores_all, scores_by_model, scores_gnn, y_test


# ── 1. kpis.json ─────────────────────────────────────────────────────────────

def export_kpis(acc, data, scores_gnn, y_test, out_dir):
    n_accounts   = int(data.num_nodes)
    n_fraud      = int((data.y == 1).sum())
    pct_fraud    = round(100 * n_fraud / n_accounts, 2)
    pr_auc_gnn   = round(float(average_precision_score(y_test, scores_gnn)), 4)
    rec_p90, _   = recall_at_precision(y_test, scores_gnn, 0.90)

    obj = {
        "n_accounts":   n_accounts,
        "n_fraud":      n_fraud,
        "pct_fraud":    pct_fraud,
        "pr_auc_gnn":   pr_auc_gnn,
        "recall_at_p90": round(float(rec_p90), 4),
        "model":        "GraphSAGE (2 capas, 64 hidden)",
        "dataset":      "Sintético — Santander AI Lab equiv.",
        "client":       "Banco Regional del Sur (BRS)",
    }
    _save(obj, f"{out_dir}/kpis.json")


# ── 2. pr_curves.json ────────────────────────────────────────────────────────

def export_pr_curves(y_test, scores_by_model, out_dir):
    def _curve(y, s, name):
        prec, rec, _ = precision_recall_curve(y, s)
        # downsample to ≤200 points to keep JSON small
        step = max(1, len(prec) // 200)
        return {
            "model":    name,
            "pr_auc":   round(float(average_precision_score(y, s)), 4),
            "precision": [round(float(p), 4) for p in prec[::step]],
            "recall":    [round(float(r), 4) for r in rec[::step]],
        }

    obj = [_curve(y_test, scores, name) for name, scores in scores_by_model.items()]
    _save(obj, f"{out_dir}/pr_curves.json")


# ── 3. score_distribution.json ────────────────────────────────────────────────

def export_score_distribution(data, scores_all, out_dir, n_bins=40):
    y_all    = data.y.numpy()
    bins     = np.linspace(0, 1, n_bins + 1)
    centers  = ((bins[:-1] + bins[1:]) / 2).tolist()

    fraud_hist, _ = np.histogram(scores_all[y_all == 1], bins=bins, density=False)
    legit_hist, _ = np.histogram(scores_all[y_all == 0], bins=bins, density=False)

    obj = {
        "bin_centers": [round(c, 3) for c in centers],
        "fraud":       fraud_hist.tolist(),
        "legit":       legit_hist.tolist(),
    }
    _save(obj, f"{out_dir}/score_distribution.json")


# ── 4. rings.json ─────────────────────────────────────────────────────────────

def export_rings(acc, txn, data, scores_all, out_dir, top_n=10):
    node_ids  = data.node_ids
    id2score  = {nid: float(scores_all[i]) for i, nid in enumerate(node_ids)}
    fraud_set = set(acc.loc[acc.is_fraud == 1, "account_id"])

    G = nx.DiGraph()
    for _, row in acc.iterrows():
        G.add_node(row.account_id, is_fraud=int(row.is_fraud),
                   balance=row.balance, risk_score=row.risk_score)
    for _, row in txn.iterrows():
        G.add_edge(row.src, row.dst, amount=row.amount,
                   timestamp=int(row.timestamp), is_fraud=int(row.is_fraud))

    Gf = G.subgraph(fraud_set).copy()
    rings = []
    try:
        for cycle in nx.simple_cycles(Gf):
            if 3 <= len(cycle) <= 10:
                rings.append(cycle)
                if len(rings) >= top_n:
                    break
    except Exception:
        pass

    out_rings = []
    for i, ring in enumerate(rings):
        nodes_data = []
        for nid in ring:
            row = acc[acc.account_id == nid].iloc[0]
            nodes_data.append({
                "id":           nid,
                "gnn_score":    round(id2score.get(nid, 0.0), 4),
                "is_fraud":     int(row.is_fraud),
                "balance":      round(float(row.balance), 2),
                "risk_score":   round(float(row.risk_score), 4),
                "account_type": row.account_type,
            })

        ring_edges = []
        total_amount = 0.0
        for j in range(len(ring)):
            src, dst = ring[j], ring[(j+1) % len(ring)]
            if G.has_edge(src, dst):
                ed = G[src][dst]
                amt = round(float(ed.get("amount", 0)), 2)
                ring_edges.append({"src": src, "dst": dst, "amount": amt})
                total_amount += amt

        out_rings.append({
            "ring_id":      i + 1,
            "n_nodes":      len(ring),
            "total_amount": round(total_amount, 2),
            "avg_score":    round(np.mean([n["gnn_score"] for n in nodes_data]), 4),
            "nodes":        nodes_data,
            "edges":        ring_edges,
        })

    _save(out_rings, f"{out_dir}/rings.json")


# ── 5. top_accounts.json ──────────────────────────────────────────────────────

def export_top_accounts(acc, txn, data, scores_all, out_dir, top_n=200):
    node_ids = data.node_ids
    feats    = build_node_features(acc, txn)

    fraud_set  = set(acc.loc[acc.is_fraud == 1, "account_id"])
    acc_idx    = acc.set_index("account_id")
    feats_idx  = feats.set_index("account_id")
    G = nx.DiGraph()
    for _, row in txn.iterrows():
        G.add_edge(row.src, row.dst, amount=row.amount)

    records = []
    for i, nid in enumerate(node_ids):
        row = acc_idx.loc[nid]
        f   = feats_idx.loc[nid] if nid in feats_idx.index else None
        records.append({
            "account_id":       nid,
            "gnn_score":        round(float(scores_all[i]), 4),
            "is_fraud":         int(row.is_fraud),
            "balance":          round(float(row.balance), 2),
            "risk_score":       round(float(row.risk_score), 4),
            "account_type":     row.account_type,
            "degree_in":        int(G.in_degree(nid)) if nid in G else 0,
            "degree_out":       int(G.out_degree(nid)) if nid in G else 0,
            "total_sent":       round(float(f["total_sent"]) if f is not None else 0, 2),
            "total_received":   round(float(f["total_received"]) if f is not None else 0, 2),
            "in_ring":          nid in fraud_set,
        })

    records.sort(key=lambda r: r["gnn_score"], reverse=True)
    _save(records[:top_n], f"{out_dir}/top_accounts.json")


# ── 6. entities.json ──────────────────────────────────────────────────────────

def export_entities(acc, txn, data, scores_all, cfg, out_dir, top_n=300):
    """
    Build entity network JSON for Cytoscape visualization.
    Focuses on top_n accounts by GNN score + their entity relationships.
    Node types: cuenta | persona | empresa
    Edge types: es_titular | es_director | transaccion
    """
    raw = cfg["data"]["raw_dir"]
    personas, empresas, titularidades, directores, pep_flags, _sanctions = _load_entity_tables(raw)

    node_ids = data.node_ids
    id2score = {nid: float(scores_all[i]) for i, nid in enumerate(node_ids)}
    acc_idx  = acc.set_index("account_id")

    # top accounts to include in the entity network
    sorted_accs = sorted(node_ids, key=lambda x: id2score.get(x, 0), reverse=True)
    top_accs = set(sorted_accs[:top_n])

    pep_set = set(pep_flags["account_id"].tolist()) if not pep_flags.empty else set()
    personas_idx = personas.set_index("account_id") if not personas.empty else pd.DataFrame()
    emp_idx = empresas.set_index("empresa_id") if not empresas.empty else pd.DataFrame()

    nodes, edges = [], []
    seen_nodes, seen_edges = set(), set()

    def _add_node(node_id, node_type, props):
        if node_id not in seen_nodes:
            seen_nodes.add(node_id)
            nodes.append({"id": node_id, "type": node_type, **props})

    def _add_edge(src, dst, rel_type, props=None):
        key = (src, dst, rel_type)
        if key not in seen_edges:
            seen_edges.add(key)
            edges.append({"src": src, "dst": dst, "type": rel_type, **(props or {})})

    # add account nodes
    for acc_id in top_accs:
        row = acc_idx.loc[acc_id]
        persona_info = {}
        if not personas_idx.empty and acc_id in personas_idx.index:
            p = personas_idx.loc[acc_id]
            persona_info = {
                "nombre_completo": str(p.get("nombre_completo", "")),
                "ocupacion":       str(p.get("ocupacion", "")),
                "municipio":       str(p.get("municipio", "")),
                "cuil":            str(p.get("cuil", "")),
            }
        _add_node(acc_id, "cuenta", {
            "label":        persona_info.get("nombre_completo", acc_id),
            "gnn_score":    round(id2score.get(acc_id, 0), 4),
            "is_fraud":     int(row.is_fraud),
            "balance":      round(float(row.balance), 2),
            "risk_score":   round(float(row.risk_score), 4),
            "account_type": row.account_type,
            "is_pep":       acc_id in pep_set,
            **persona_info,
        })

    # titularidades: link empresas to top accounts
    if not titularidades.empty:
        emp_titularidades = titularidades[
            (titularidades["titular_type"] == "empresa") &
            (titularidades["account_id"].isin(top_accs))
        ]
        for _, row in emp_titularidades.iterrows():
            emp_id = row["titular_id"]
            if not emp_idx.empty and emp_id in emp_idx.index:
                emp = emp_idx.loc[emp_id]
                _add_node(emp_id, "empresa", {
                    "label":             str(emp["razon_social"]),
                    "razon_social":      str(emp["razon_social"]),
                    "cuit_empresa":      str(emp["cuit_empresa"]),
                    "sector":            str(emp["sector"]),
                    "pais_constitucion": str(emp["pais_constitucion"]),
                    "is_shell":          bool(emp["is_shell"]),
                })
                _add_edge(emp_id, row["account_id"], "es_titular", {
                    "porcentaje": int(row.get("porcentaje_titularidad", 100))
                })

    # directores: link personas (accounts) to empresas in network
    if not directores.empty and not emp_idx.empty:
        visible_emps = {n["id"] for n in nodes if n["type"] == "empresa"}
        dir_links = directores[
            (directores["persona_id"].isin(top_accs)) &
            (directores["empresa_id"].isin(visible_emps))
        ]
        for _, row in dir_links.iterrows():
            _add_edge(row["persona_id"], row["empresa_id"], "es_director", {
                "cargo": str(row["cargo"]),
                "vigente": bool(row.get("vigente", True)),
            })

    _save({"nodes": nodes, "edges": edges}, f"{out_dir}/entities.json")


# ── 7. cases.json ─────────────────────────────────────────────────────────────

def export_cases(acc, txn, data, scores_all, cfg, out_dir, n_cases=80):
    """
    Pre-generate alert cases for the case management module.
    Takes top scored accounts + all confirmed fraud nodes.
    Each case includes full context: entity, transactions, neighbors, pattern.
    """
    raw = cfg["data"]["raw_dir"]
    seed = cfg["project"]["seed"]
    rng = np.random.default_rng(seed + 99)
    random.seed(seed + 99)

    personas, empresas, titularidades, directores, pep_flags, sanctions_hits = _load_entity_tables(raw)

    node_ids = data.node_ids
    id2idx   = {nid: i for i, nid in enumerate(node_ids)}
    id2score = {nid: float(scores_all[i]) for i, nid in enumerate(node_ids)}
    acc_idx  = acc.set_index("account_id")

    personas_idx = personas.set_index("account_id") if not personas.empty else pd.DataFrame()
    emp_idx      = empresas.set_index("empresa_id") if not empresas.empty else pd.DataFrame()
    pep_set      = set(pep_flags["account_id"].tolist()) if not pep_flags.empty else set()
    # account_id → hit de screening (a lo sumo uno por cuenta, ver generate_sanctions_hits)
    sanctions_idx = (
        {r["account_id"]: r for r in sanctions_hits.to_dict("records")}
        if not sanctions_hits.empty else {}
    )

    # ── rules engine: deterministic AML scenarios evaluated alongside the GNN ──
    feats = build_node_features(acc, txn)
    rules_by_acc = rules_engine.evaluate(feats, cfg)

    def _rules(acc_id, screening):
        """Fired rules for an account: transactional (R01-R07) + R08 (screening)."""
        ids = list(rules_by_acc.get(acc_id, {}).get("rules_fired", []))
        if screening.get("hit_directo") or screening.get("exposicion_indirecta"):
            ids.append("R08")  # sanctions/watchlist exposure
        rules_fired = [
            {k: rules_engine.RULES_BY_ID[rid][k]
             for k in ("id", "nombre", "cita", "severidad", "descripcion")}
            for rid in ids
        ]
        return {"rules_fired": rules_fired,
                "rule_score": rules_engine.score_from_ids(ids, cfg)}

    # transaction graph for neighbor lookups
    G = nx.DiGraph()
    for _, row in txn.iterrows():
        G.add_edge(row.src, row.dst, amount=float(row.amount),
                   timestamp=int(row.timestamp), is_fraud=int(row.is_fraud))

    # candidate accounts: all fraud + top scored legit (high-risk alerts)
    fraud_ids = set(acc.loc[acc.is_fraud == 1, "account_id"])
    sorted_by_score = sorted(node_ids, key=lambda x: id2score.get(x, 0), reverse=True)
    candidates = list(dict.fromkeys(
        [x for x in sorted_by_score if x in fraud_ids] +
        sorted_by_score[:n_cases]
    ))[:n_cases]

    # ground-truth typology from the generator (accounts.csv), when present
    typ_map = (
        acc.set_index("account_id")["fraud_typology"].fillna("").to_dict()
        if "fraud_typology" in acc.columns else {}
    )

    def _pattern(acc_id):
        # prefer the labelled typology emitted by the generator
        label = typ_map.get(acc_id) or ""
        if label:
            return label
        # fallback heuristic for high-scored accounts without a ground-truth label
        nbrs = list(G.predecessors(acc_id)) + list(G.successors(acc_id))
        nbr_fraud = sum(1 for n in nbrs if n in fraud_ids)
        if nbr_fraud >= 3:
            return "anillo_lavado"
        out_txns = [G[acc_id][d]["amount"] for d in G.successors(acc_id)]
        if len(out_txns) >= 4 and max(out_txns, default=0) < 10000:
            return "estructuracion"
        if G.in_degree(acc_id) >= 5:
            return "agregacion_fondos"
        return "transacciones_inusuales"

    def _empresa_info(acc_id):
        if titularidades.empty:
            return None
        row = titularidades[
            (titularidades["account_id"] == acc_id) &
            (titularidades["titular_type"] == "empresa")
        ]
        if row.empty:
            return None
        emp_id = row.iloc[0]["titular_id"]
        if emp_idx.empty or emp_id not in emp_idx.index:
            return None
        e = emp_idx.loc[emp_id]
        return {
            "empresa_id":      emp_id,
            "razon_social":    str(e["razon_social"]),
            "cuit_empresa":    str(e["cuit_empresa"]),
            "sector":          str(e["sector"]),
            "pais_constitucion": str(e["pais_constitucion"]),
            "is_shell":        bool(e["is_shell"]),
        }

    def _neighbors(acc_id, top_k=6):
        nbrs = list(G.predecessors(acc_id)) + list(G.successors(acc_id))
        nbrs = list(set(nbrs) - {acc_id})
        nbrs.sort(key=lambda x: id2score.get(x, 0), reverse=True)
        result = []
        for n in nbrs[:top_k]:
            direction = "entrada" if n in G.predecessors(acc_id) else "salida"
            row = acc_idx.loc[n] if n in acc_idx.index else None
            result.append({
                "account_id": n,
                "gnn_score":  round(id2score.get(n, 0), 4),
                "is_fraud":   int(acc_idx.loc[n, "is_fraud"]) if n in acc_idx.index else 0,
                "direction":  direction,
                "amount":     round(G[n][acc_id]["amount"] if direction == "entrada" and G.has_edge(n, acc_id)
                                    else G[acc_id][n]["amount"] if G.has_edge(acc_id, n) else 0, 2),
            })
        return result

    def _screening(acc_id, neighbors):
        """
        Screening de sanciones — hit directo sobre la cuenta + exposición
        indirecta (la cuenta transaccionó con alguien que sí está en una
        lista). Es la capacidad que la landing promete: no solo alertar al
        que está en la lista, sino a quien está a un salto de distancia.
        """
        direct = sanctions_idx.get(acc_id)
        indirecta = []
        for n in neighbors:
            h = sanctions_idx.get(n["account_id"])
            if h:
                indirecta.append({
                    "account_id":          n["account_id"],
                    "direction":           n["direction"],
                    "lista":               h["lista"],
                    "nombre_coincidencia": h["nombre_coincidencia"],
                    "motivo":              h["motivo"],
                    "score_match":         round(float(h["score_match"]), 2),
                    "estado":              h["estado"],
                })
        return {
            "hit_directo": ({
                "lista":               direct["lista"],
                "nombre_coincidencia": direct["nombre_coincidencia"],
                "motivo":              direct["motivo"],
                "score_match":         round(float(direct["score_match"]), 2),
                "estado":              direct["estado"],
            } if direct is not None else None),
            "exposicion_indirecta": indirecta,
        }

    def _dst_type(dst):
        return acc_idx.loc[dst, "account_type"] if dst in acc_idx.index else None

    def _recent_txns(acc_id, top_k=10):
        rows = []
        for src, dst, d in list(G.in_edges(acc_id, data=True)) + list(G.out_edges(acc_id, data=True)):
            direction = "entrada" if dst == acc_id else "salida"
            row = {"src": src, "dst": dst, "amount": round(d["amount"], 2),
                   "timestamp": d["timestamp"], "direction": direction,
                   "is_fraud": d["is_fraud"]}
            row.update(_txn_meta(src, dst, d["amount"], _dst_type(dst)))
            rows.append(row)
        rows.sort(key=lambda x: x["timestamp"], reverse=True)
        return rows[:top_k]

    # ── traceability: multi-hop money trail (upstream to origin + layering out) ──
    perp_set = set()
    ot_path = Path(out_dir) / "origin_trace.json"
    if ot_path.exists():
        try:
            perp_set = {p["node_id"] for p in json.loads(ot_path.read_text())["perpetrators"]}
        except Exception:
            perp_set = set()

    def _name(nid):
        if not personas_idx.empty and nid in personas_idx.index:
            v = personas_idx.loc[nid].get("nombre_completo")
            return str(v) if pd.notna(v) else None
        return None

    def _hop(src, dst):
        d = G[src][dst]
        hop = {
            "from": src, "to": dst,
            "amount": round(float(d["amount"]), 2),
            "timestamp": int(d["timestamp"]),
            "is_fraud_edge": int(d["is_fraud"]),
        }
        hop.update(_txn_meta(src, dst, d["amount"],
                             acc_idx.loc[dst, "account_type"] if dst in acc_idx.index else None))
        return hop

    def _traceability(acc_id, max_depth=6):
        """
        Reconstruct the money trail around a case account:
          - upstream: walk backward along the largest *fraudulent* inflow, hop by
            hop, until reaching an origin (a known perpetrator or a node with no
            fraudulent inflow). Cycle-safe (round-tripping schemes are cyclic).
          - downstream: the layering exits — outgoing edges, largest first.
        Returns ordered hops (origin first → case account → exits).
        """
        upstream, visited, cur = [], {acc_id}, acc_id
        for _ in range(max_depth):
            in_edges = [(s, G[s][cur]) for s in G.predecessors(cur) if s not in visited]
            fraud_in = [(s, d) for s, d in in_edges if d["is_fraud"] == 1]
            pool = fraud_in or [(s, d) for s, d in in_edges
                                if s in fraud_ids or id2score.get(s, 0) > 0.5]
            if not pool:
                break
            s, _d = max(pool, key=lambda x: x[1]["amount"])
            hop = _hop(s, cur)
            hop.update({
                "from_gnn_score": round(id2score.get(s, 0), 4),
                "from_is_fraud":  int(acc_idx.loc[s, "is_fraud"]) if s in acc_idx.index else 0,
                "from_is_perp":   s in perp_set,
                "from_name":      _name(s),
            })
            upstream.append(hop)
            visited.add(s)
            cur = s
            if s in perp_set:
                break
        upstream.reverse()  # origin first → case account last

        out_edges = sorted(
            ((dst, G[acc_id][dst]) for dst in G.successors(acc_id)),
            key=lambda x: x[1]["amount"], reverse=True,
        )
        downstream = []
        for dst, _d in out_edges[:6]:
            hop = _hop(acc_id, dst)
            hop.update({
                "to_gnn_score": round(id2score.get(dst, 0), 4),
                "to_is_fraud":  int(acc_idx.loc[dst, "is_fraud"]) if dst in acc_idx.index else 0,
                "to_name":      _name(dst),
            })
            downstream.append(hop)

        origin = None
        if upstream:
            h = upstream[0]
            origin = {
                "account_id": h["from"], "gnn_score": h["from_gnn_score"],
                "is_fraud": h["from_is_fraud"], "is_perp": h["from_is_perp"],
                "name": h["from_name"], "amount": h["amount"],
            }
        return {"upstream": upstream, "downstream": downstream, "origin": origin}

    base_date = datetime(2026, 6, 1)

    # Ley 25.246 (UIF Argentina), art. 21 inc. b — plazo máximo para que un
    # sujeto obligado reporte una Operación Sospechosa (ROS) desde que la
    # detecta: 150 días corridos para entidades financieras/bancarias.
    DIAS_PLAZO_ROS = 150

    # Pool de analistas de compliance (ficticio) — asignación determinística
    # por caso, no por cuenta, para distribuir la carga de forma pareja.
    ANALISTAS = [
        "Lic. Valentina Ibarra",
        "Lic. Tomás Ferreyra",
        "Lic. Camila Suárez",
        "Lic. Nicolás Paredes",
        "Lic. Agustina Domínguez",
    ]

    cases = []
    for i, acc_id in enumerate(candidates):
        row = acc_idx.loc[acc_id]
        persona = {}
        if not personas_idx.empty and acc_id in personas_idx.index:
            p = personas_idx.loc[acc_id]
            persona = {k: str(p[k]) if pd.notna(p[k]) else "" for k in p.index}

        alert_dt   = base_date + timedelta(days=int(rng.integers(0, 45)))
        alert_date = alert_dt.strftime("%Y-%m-%d")
        vencimiento_ros = (alert_dt + timedelta(days=DIAS_PLAZO_ROS)).strftime("%Y-%m-%d")
        score = id2score.get(acc_id, 0)
        neighbors = _neighbors(acc_id)
        screening = _screening(acc_id, neighbors)
        rules = _rules(acc_id, screening)

        cases.append({
            "case_id":      f"CASO-{i+1:05d}",
            "account_id":   acc_id,
            "gnn_score":    round(score, 4),
            "is_fraud":     int(row.is_fraud),
            "alert_date":   alert_date,
            "status":       "abierto",
            "pattern":      _pattern(acc_id),
            "is_pep":       acc_id in pep_set,
            "balance":      round(float(row.balance), 2),
            "risk_score":   round(float(row.risk_score), 4),
            "account_type": row.account_type,
            "analista_asignado": ANALISTAS[int(rng.integers(0, len(ANALISTAS)))],
            "dias_plazo_ros":    DIAS_PLAZO_ROS,
            "vencimiento_ros":   vencimiento_ros,
            "screening":    screening,
            "rule_score":   rules["rule_score"],
            "rules_fired":  rules["rules_fired"],
            "persona":      persona,
            "empresa":      _empresa_info(acc_id),
            "neighbors":    neighbors,
            "recent_transactions": _recent_txns(acc_id),
            "traceability": _traceability(acc_id),
        })

    _save(cases, f"{out_dir}/cases.json")
    _save(rules_engine.catalogue(), f"{out_dir}/rules_catalog.json")

    n_with_rules = sum(1 for c in cases if c["rules_fired"])
    print(f"  reglas AML: {n_with_rules}/{len(cases)} casos con >=1 regla disparada")


# ── master ────────────────────────────────────────────────────────────────────

def export_all(config_path="config/config.yaml"):
    cfg     = load_config(config_path)
    out_dir = cfg["paths"]["dashboard_data_dir"]
    Path(out_dir).mkdir(parents=True, exist_ok=True)

    print("=" * 55)
    print("  Exportando JSONs para dashboard")
    print("=" * 55)

    acc, txn, data, scores_all, scores_by_model, scores_gnn, y_test = load_all(cfg)

    export_kpis(acc, data, scores_gnn, y_test, out_dir)
    export_pr_curves(y_test, scores_by_model, out_dir)
    export_score_distribution(data, scores_all, out_dir)
    export_rings(acc, txn, data, scores_all, out_dir)
    export_top_accounts(acc, txn, data, scores_all, out_dir)
    export_entities(acc, txn, data, scores_all, cfg, out_dir)
    export_cases(acc, txn, data, scores_all, cfg, out_dir)

    # check total size
    total_kb = sum(p.stat().st_size for p in Path(out_dir).glob("*.json")) / 1024
    print(f"\n  Total JSONs: {total_kb:.1f} KB  "
          f"({'OK' if total_kb < 2048 else 'ATENCIÓN: supera 2MB'})")
    print("=" * 55)


if __name__ == "__main__":
    export_all()
